### ISSUE TITLE
Place Search

### ISSUE THREAD

**Issue by caacree** [jolavb/Sno_Demo#15]
I'm not sure this is REALLY a requirement, something simpler like just automatically starting in the current location might be fine, since this is supposedly going to take place on site, but look at it and decide the best way. Having them input some coordinates to start wouldn't be the end of the world if there isn't an easy-to-use API we can just integrate with.

**Comment by jolavb** [comment]
Looks like ol-geocoder is what we're looking for. Just pushed a branch with it included if you're interested in taking a look. Basically a search box which autofills while you type. When place is selected it relocates map to that place and throws down a marker. I'm thinking we could use that to set a new center point so that when a user needs to zoom back out they do so using that point as the center.
Before I PR this I'm going to get it into true ol map control form.

**Comment by caacree** [comment]
https://github.com/jolavb/Sno_Demo/pull/25
